### ISSUE TITLE
some typos in example/convert.py

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/gnpy#16]
I can not execute convert.py and found some typos : some  'f' characters on lines 26, 36, 45, 48, 88, 96, 88 eg: ValueError(f' ...') are not supported by my python and line numbers are not correct on lines 23 and 33 : should be 4 instead of 5 since header is on line 4 in the excel file example (starting numbering from 0)

**Comment by giladg-FB** [comment]
Please note these are f-strings notations, introduced in python 3.6. The goal is to support the latest version of python, avoiding any backward compatibility workload. You can setup a virtual environment and install/use gnpy under that environment. Since it's platform-dependent, I can't instruct on how to do that, but a quick web search ("python 3 virtual environment" + platform keywords) should get you going. Please close thread, or post further issues if this doesn't resolve the problem.

**Comment by EstherLerouzic** [comment]
Thank you for your answer. I missed the python3.6 requirement, sorry for that.
