### ISSUE TITLE
master:examples don't work with python3

### ISSUE THREAD

**Issue by ggrammel** [Telecominfraproject/gnpy#68]
2018-04-26
tested with python2 but got errors while python3 looks fine. 

For a quick fix and to resolve ambiguity, the README file describing how to run examples in master should require be run with python3:
`python3 transmission_main_example.py` and
`python3 transmission_main_example.py coronet_conus_example.json`

are we running tests against such errors?

Note: classified as a bug since users trying to run examples but having only python2 installed will run into the issue which throws an error.

---
ggrammel-mbp:examples ggrammel$ **python2 transmission_main_example.py**
  File "transmission_main_example.py", line 35
    f'#{idx} Carrier(frequency={c.frequency},\n  power=Power(signal={c.power.signal}, nli={c.power.nli}, ase={c.power.ase}))'
                                                                                                                            ^
SyntaxError: invalid syntax

ggrammel-mbp:examples ggrammel$ **python3 transmission_main_example.py**
invalid souce node specified: '', replaced with Transceiver Site_A
invalid destination node specified: '', replaced with Transceiver Site_B
There are 4 network elements between Transceiver Site_A and Transceiver Site_B
Transceiver Site_A
Fiber Span1
  length (m): 80000.00
  loss (dB):  16.00
Edfa Edfa1
  type_variety:      std_low_gain
  gain (dB):         16.00
  noise figure (dB): 7.12
  Power In (dBm):    3.83
  Power Out (dBm):   19.83
Transceiver Site_B
  OSNR ASE (1nm):        34.83
  OSNR ASE (signal bw):  30.75
  SNR total (signal bw): 27.36
ggrammel-mbp:examples ggrammel$

**Comment by giladg-FB** [comment]
Python 2 is not supported. Not a bug.

Sent from my iPhone

On Apr 26, 2018, at 7:55 AM, Gert Grammel <notifications@github.com<mailto:notifications@github.com>> wrote:


2018-04-26
tested with python2 but got errors while python3 looks fine.

For a quick fix and to resolve ambiguity, the README file describing how to run examples in master should require be run with python3:
python3 transmission_main_example.py and
python3 transmission_main_example.py coronet_conus_example.json

are we running tests against such errors?

Note: classified as a bug since users trying to run examples but having only python2 installed will run into the issue which throws an error.

________________________________

ggrammel-mbp:examples ggrammel$ python2 transmission_main_example.py
File "transmission_main_example.py", line 35
f'#{idx} Carrier(frequency={c.frequency},\n power=Power(signal={c.power.signal}, nli={c.power.nli}, ase={c.power.ase}))'
^
SyntaxError: invalid syntax

ggrammel-mbp:examples ggrammel$ python3 transmission_main_example.py
invalid souce node specified: '', replaced with Transceiver Site_A
invalid destination node specified: '', replaced with Transceiver Site_B
There are 4 network elements between Transceiver Site_A and Transceiver Site_B
Transceiver Site_A
Fiber Span1
length (m): 80000.00
loss (dB): 16.00
Edfa Edfa1
type_variety: std_low_gain
gain (dB): 16.00
noise figure (dB): 7.12
Power In (dBm): 3.83
Power Out (dBm): 19.83
Transceiver Site_B
OSNR ASE (1nm): 34.83
OSNR ASE (signal bw): 30.75
SNR total (signal bw): 27.36
ggrammel-mbp:examples ggrammel$

**Comment by ggrammel** [comment]
If Python2 is not supported it should be documented in the Readme to make sure the the examples run fine. 
So the bug is then in the Readme

**Comment by dutc** [comment]
This is detailed in the onboarding guide. Python 2 will not be supported.

https://mail.python.org/pipermail/python-dev/2018-March/152348.html

**Comment by ggrammel** [comment]
Many folks still have python2 installed. As discussed above, if Python2 is not supported, it shoud be stated in the Readme. We can add a warning to the README or make it explicit to use python3 in the examples, but the issue needs to be addressed.

**Comment by dutc** [comment]
Currently, this project is focussed on code development. This means moving faster at developing features by making a set of common assumptions:

- that users know the difference between Python 2 and Python 3
- that users are equipped to make code contributions in Python 3
    - that users will have Python 3 installed
    - that users understand virtual environments, how to install code via `setup.py`, and how this differs from `pip` installation
    - that users understand `PYTHONPATH`/`PYTHONHOME` and various details of how Python code is executed

If you want to include a "Quick Start Guide for Non-Coders," we can include that in the README. This can document common aspects of how Python works for non-coding users.

However, for non-coders (for folks for whom the above are not a given,) our Binder or Azure Notebook Service solution are the proposed workflows. These provide *no-install*, *one-click* access to our demos.

We should strongly guide non-technical users toward this solution so that we can focus our efforts on feature development and code quality improvement.

Feel free to submit a pull request with any additional README changes you would like. These will be reviewed via our normal code review process. Please ensure that the PR addresses a single issue to ease in review. There is no need to open a Github issue corresponding to each PR.

**Comment by ggrammel** [comment]
Keep in mind that individuals looking at the master branch are neither code contributors nor greenhorns who never touched a piece of code. If there is confusion about the target type of users for experiencing gnpy, feel free to reach out to the WG Chairs for guidance. A "Quick Start Guide for Non-Coders" might be a useful addition. It doesn't obviate the need for a workable README though. The latter aspect is tracked in https://github.com/Telecominfraproject/gnpy/issues/55
